export const portfolioData = [
  {
    id: 1,
    title: "Real-Time Weather App",
    category: "Featured Project",
    description: "A dynamic weather forecasting web application built with JavaScript. Fetches real-time meteorological data, displaying atmospheric conditions, temperature trends, and location-based updates instantly.",
    image: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1000&q=80",
    liveLink: "https://weather-forecast-app-six-lemon.vercel.app/",
    githubLink: "https://github.com/HamnaTanveer/weather-forecast-app",
  },
  {
    id: 2,
    title: "Bookstore App with APIs",
    category: "Featured Project",
    description: "An interactive digital library platform integrated with external REST APIs. Allows users to explore extensive book catalogs, search titles dynamically, and view detailed publication summaries.",
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=1000&q=80",
    liveLink: "https://book-store-app-sable-two.vercel.app/",
    githubLink: "https://github.com/HamnaTanveer/BookStore-App",
  },
  {
    id: 3,
    title: "Mophy Payment Admin Theme",
    category: "Featured Project",
    description: "A sleek, modern financial admin dashboard concept featuring comprehensive payment tracking, interactive analytics charts, income-expense summaries, and a high-performance management UI built with React.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=80",
    liveLink: "http://mophy-payment-admin-dashboard-g21j-gamma.vercel.app/",
    githubLink: "https://github.com/HamnaTanveer/mophy-payment-admin-dashboard",
  },
  {
    id: 4,
    title: "E-Commerce Shopping Website",
    category: "Featured Project",
    description: "An advanced online shopping platform developed using React.js. Features dynamic product filtering options, seamless category sorting, interactive cart handling, and a responsive modern user interface.",
    image: "/Shopping.jpeg",
    liveLink: "https://shopping-cart-app-q72w.vercel.app/",
    githubLink: "https://github.com/HamnaTanveer/shopping-cart-app",
  },
  {
    id: 5,
    title: "Interactive Todo List App",
    category: "Featured Project",
    description: "A clean, efficient productivity application built to manage day-to-day tasks. Includes smooth state management, item filtering, local storage persistence, and a minimalist design aesthetic.",
    image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=1000&q=80",
    liveLink: "https://todo-list-app-red-ten.vercel.app/",
    githubLink: "https://github.com/HamnaTanveer/todo-list-app",
  },
];